platform :ios, '12.0'

use_frameworks!

target 'SFaceCompare_Example' do
  pod 'SFaceCompare', :path => '../'

  target 'SFaceCompare_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
