use_frameworks!

target 'SFaceCompare_Example' do
  pod 'SFaceCompare', :path => '../'

  target 'SFaceCompare_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
